# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ba9652fbf553ca07716dea467f244cfffe8644d46bb52336393c3a4cb40d19e7be346c76e6629a413d831c00855efecb9d7d16da4ce5251ca7f59badd82bb76

test:
  secret_key_base: f4eb47ea850afa85812aa4eb72c9cf3df4a72d49ef2ce42cbc7ed8842edf0dc729849c3816c5d0e544791022967ce69120b0135cf020791658de9a4a609abbf5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
