theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: left
theme_advanced_statusbar_location: bottom
theme_advanced_buttons3_add:
  - tablecontrols
  - fullscreen
plugins:
  - table
  - fullscreen
  - advlist
  - autolink
  - lists
  - link
  - image
  - charmap
  - print
  - preview
  - hr
  - anchor
  - pagebreak
  - searchreplace
  - wordcount
  - visualblocks
  - visualchars
  - code
  - insertdatetime
  - media
  - nonbreaking
  - save
  - contextmenu
  - directionality
  - emoticons
  - template
  - paste
  - textcolor
  - colorpicker
  - textpattern
  - imagetools
  - codesample
  - toc
theme: 'modern'
image_advtab: true
